const reviews = [
  {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  },
  {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  },
  {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  },
  {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  },
  {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  },
  {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  },
  {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  },
  {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  },
  {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  },
  {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  }, {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  }, {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  }, {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  }, {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  }, {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  }, {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  }, {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  }, {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  }, {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  }, {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  }, {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  }, {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  }, {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  }, {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  }, {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  }, {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  }, {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  }, {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  }, {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  }, {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  },
  {
    "url": "urlslslsls",
    "text": "urlslslsls",
    "name": "urlslslsls",
    "key": "urlslslsls",
    "avatar": "urlslslsls",
    best: true,
  }
]

export default function getReviews(){
  return reviews
}